# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'marvel-characters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for marvel-characters
  pod 'Alamofire', '~> 5.2'
  pod 'lottie-ios'

  target 'marvel-charactersTests' do
    inherit! :search_paths
    
  end

  target 'marvel-charactersUITests' do
    # Pods for testing
  end

end
