# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Marvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel
	  pod 'Swinject'
	  pod 'SwinjectAutoregistration'
    pod 'lottie-ios'
    pod 'Kingfisher'

  target 'MarvelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelUITests' do
    # Pods for testing
  end

end
