# Uncomment the next line to define a global platform for your project
 platform :ios, '14.1'

target 'CharactersMarvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CharactersMarvel
  pod  'lottie-ios'
  
  target 'CharactersMarvelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
