# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelCharactersShowcase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelCharactersShowcase
    pod "Hash"

  target 'MarvelCharactersShowcaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelCharactersShowcaseUITests' do
    # Pods for testing
  end

end
