# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelCharacters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MarvelCharacters
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'Swinject'

target 'MarvelCharactersTests' do
  inherit! :search_paths
  # Pods for testing
  pod 'RxBlocking', '6.5.0'
  pod 'RxTest', '6.5.0'
end

target 'MarvelCharactersUITests' do
  # Pods for testing
end

end
